In [9]:
import numpy as np

In [10]:
lista = [1,2,3,4,5,6,7,8,9,10]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arreglo2 = np.array(lista1)
arreglo2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
type(arreglo)

numpy.ndarray

In [15]:
arreglo.dtype

dtype('int64')

In [16]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [17]:
np.array(arreglo, dtype=np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arreglo.astype(np.float32)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [20]:
arreglo.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
promedio = np.mean(arreglo)
promedio

5.5

In [22]:
mediana =np.median(arreglo)
mediana

5.5

In [23]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

In [24]:
arreglo_de_unos = np.ones(30)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
arreglo_de_ceros = np.zeros(54)
arreglo_de_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [26]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.48329812, 0.10834589, 0.39333713, 0.97404611, 0.91053958,
       0.62017856, 0.85665141, 0.45687316, 0.22439286, 0.52846684])

In [27]:
arreglo_aleatorio2 = np.random.randint(1,200,10)
arreglo_aleatorio2

array([ 85,  12, 185,  15, 100,  58, 170,  47,  10,  73])

In [28]:
matriz = np.random.rand(3,3)
matriz

array([[0.80632617, 0.28216003, 0.11697907],
       [0.39775021, 0.98510324, 0.18498696],
       [0.06360275, 0.41484547, 0.10000614]])

In [29]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[63, 38, 60, 72, 45, 12, 24, 23, 29, 82],
       [ 4, 77, 41, 57, 26, 81, 21,  7, 51, 23],
       [89, 20, 71,  6, 60, 22, 33, 14, 53, 79],
       [61, 80, 81, 68, 66,  3, 62, 63, 93, 87],
       [98, 95, 37, 48, 92, 13, 59, 67, 49, 96],
       [29, 66, 56, 39, 73, 39, 77, 40, 28,  5],
       [18, 97, 98, 99, 45, 98, 55, 44, 13, 10],
       [48, 43, 68, 25, 75, 77, 55, 37, 43, 61],
       [84, 51, 46, 42, 43, 69, 55, 92, 63, 85],
       [93, 98, 77, 20, 19,  9, 89, 11, 18, 30]])